# docker-compose.yml (root directory)
version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tfb_studios
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/tfb_studios
      ACCESS_TOKEN_SECRET: supersecretkey123
      REFRESH_TOKEN_SECRET: refreshsupersecretkey456
    depends_on:
      - db
    ports:
      - "5001:5001"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tfb.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
